[[repos]]
repo = "local"
hooks = [
  {
    id = "cargo-fmt",
    name = "cargo +nightly fmt",
    language = "system",
    entry = "cargo +nightly fmt --all",
    files = "\\.rs$",
    pass_filenames = false,
  },
]
